### PR TITLE
Compatibility with ui.router 1.0.0+

### PR DESCRIPTION
**Pull request by pedropapa**

### CODE REVIEW

**Comment by riggerthegeek** [comment]
Thanks for the request @pedropapa - the Travis tests will need to pass before I can merge in

**Comment by riggerthegeek** [comment]
Assume you're currently working on this - it's best to use Node v6 on travis (that being the current LTS)

**Comment by pedropapa** [comment]
@riggerthegeek alright, I'll fix Travis and commit it again, give me a min.

**Comment by riggerthegeek** [comment]
Can you update the README file with the link to the UI Router 1.x.x docs page please?

I shall release this as a major update as I'll want to keep v1.x.x with support for the older versions of UI Router (I suspect it'll be a breaking change anyway)

**Comment by pedropapa** [comment]
@riggerthegeek Thanks!

**Pull request merged**
