### PR TITLE
Resolving Issue #2 (bower invalid meta).

### PR DESCRIPTION
**Pull request by tomholford**
Inspired by this commit:

https://github.com/ansukla/ng-perf/commit/e768a07c823548979752fd8c27860f6ff8a7a26f

### CODE REVIEW

**Comment by riggerthegeek** [comment]
Have merged this. As it's bower, I shouldn't need to publish a new version should I?

**Comment by tomholford** [comment]
Hmm, cleaned my bower cache and tried reinstalling in a project:

```
$ bower install ng-page-title --save
bower ng-page-title#*       not-cached https://github.com/riggerthegeek/ng-page-title.git#*
bower ng-page-title#*          resolve https://github.com/riggerthegeek/ng-page-title.git#*
bower ng-page-title#*         checkout v1.3.0
bower ng-page-title#*     invalid-meta The "main" field cannot contain minified files
bower ng-page-title#*         resolved https://github.com/riggerthegeek/ng-page-title.git#1.3.0
bower ng-page-title#^1.3.0     install ng-page-title#1.3.0
ng-page-title#1.3.0 bower_components/ng-page-title
```

But the minified .js is still listed the 'main' entry. Perhaps a version bump is needed?

**Comment by riggerthegeek** [comment]
Have released v1.3.1 to bower/npm

**Comment by tomholford** [comment]
Success :)

```
$ bower install ng-page-title --save
bower not-cached    https://github.com/riggerthegeek/ng-page-title.git#*
bower resolve       https://github.com/riggerthegeek/ng-page-title.git#*
bower checkout      ng-page-title#v1.3.1
bower resolved      https://github.com/riggerthegeek/ng-page-title.git#1.3.1
bower install       ng-page-title#1.3.1

ng-page-title#1.3.1 bower_components/ng-page-title
```

**Pull request merged**
